force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{0}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Amount_Invoice_Line_Items__c.field-meta.xml
<CustomField>
    <fullName>Amount_Invoice_Line_Items__c</fullName>
    <label>Amount Invoice Line Items</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/InvoiceUtils.cls
/**
 * @name: InvoiceUtils
 * @description: Apex Utils class for Invoice__c object
 * @test: InvoiceUtils_Test
 * @author: Richard Soto - richardsoto@outlook.com
 * @version: 0.1
 * @history
 * =======
 * v0.1 - 2021-06-22 - Initial version
 */
public with sharing class InvoiceUtils {

	/**
	 * @name: calculateAmountILIs
	 * @description: Method for calculating Amount_Invoice_Line_Items__c field
	 * @author: Richard Soto - richardsoto@outlook.com
	 * @version: 0.1
	 * @param: N/A
	 * @return: N/A
	 * @history
	 * =======
	 * v0.1 - 2021-06-21 - Initial version
	 */
	public static void calculateAmountILIs() {}
}